# Generated by Django 4.2.1 on 2023-06-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parameter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_produk',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data_produk',
            name='unit',
            field=models.CharField(choices=[('Gitar Akustik 0-12 Fret', 'Gitar Akustik 0-12 Fret'), ('Gitar Akustik 00-12 Fret', 'Gitar Akustik 00-12 Fret'), ('Gitar Akustik 00-14 Fret', 'Gitar Akustik 00-14 Fret'), ('Gitar Akustik 000-12 Fret', 'Gitar Akustik 000-12 Fret'), ('Gitar Akustik 000-14 Fret', 'Gitar Akustik 000-14 Fret'), ('Gitar Akustik Size S/Terz 12 Fret', 'Gitar Akustik Size S/Terz 12 Fret'), ('Gitar Akustik J-14 Fret', 'Gitar Akustik J-14 Fret'), ('Gitar Akustik M 14 Fret', 'Gitar Akustik M 14 Fret'), ('Gitar Akustik Elektrik', 'Gitar Akustik Elektrik'), ('Gitar Akustik Bass', 'Gitar Akustik Bass'), ('Gitar Akustik 12 String', 'Gitar Akustik 12 String'), ('Gitar Akustik Grand J-14 Fret', 'Gitar Akustik Grand J-14 Fret'), ('Gitar Akustik 14 Fret Grand Performance', 'Gitar Akustik 14 Fret Grand Performance'), ('Gitar Akustik Little Martin', 'Gitar Akustik Little Martin'), ('Faith Guitar FM', 'Faith Guitar FM'), ('Faith Guitar FV', 'Faith Guitar FV'), ('Faith Guitar FS', 'Faith Guitar FS'), ('Faith Guitar FJ', 'Faith Guitar FJ'), ('Faith Guitar FJCE', 'Faith Guitar FJCE'), ('Ukulele Soprano AS', 'Ukulele Soprano AS'), ('Ukulele Soprano MS', 'Ukulele Soprano MS'), ('Ukulele Soprano ASD', 'Ukulele Soprano ASD'), ('Ukulele Soprano MSD', 'Ukulele Soprano MSD'), ('Ukulele Soprano AC', 'Ukulele Soprano AC'), ('Ukulele Conser MC', 'Ukulele Conser MC'), ('Ukulele Conser ACD', 'Ukulele Conser ACD'), ('Ukulele Conser MCD', 'Ukulele Conser MCD'), ('Ukulele Tenor AT', 'Ukulele Tenor AT'), ('Ukulele Tenor MT', 'Ukulele Tenor MT'), ('Ukulele Tenor ATD', 'Ukulele Tenor ATD'), ('Ukulele Tenor MTD', 'Ukulele Tenor MTD'), ('Ukulele Baritone AB', 'Ukulele Baritone AB'), ('Ukulele Baritone MB', 'Ukulele Baritone MB'), ('Ukulele Baritone ABD', 'Ukulele Baritone ABD'), ('Ukulele Baritone MBD', 'Ukulele Baritone MBD')], max_length=100),
        ),
    ]
