# Generated by Django 4.2.1 on 2023-06-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parameter', '0002_alter_data_produk_product_alter_data_produk_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_produk',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
