# Generated by Django 4.2.1 on 2023-07-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parameter', '0003_alter_data_produk_unit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='getempdetails',
            table='auth_users',
        ),
    ]
