# Generated by Django 4.2.1 on 2023-07-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parameter', '0004_alter_getempdetails_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='getempdetails',
            table='getempdetails',
        ),
    ]
