# Generated by Django 4.2.1 on 2023-07-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deskriptif', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data_mentah',
            new_name='data_preparation',
        ),
    ]
