# Generated by Django 4.2.1 on 2023-07-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deskriptif', '0002_rename_data_mentah_data_preparation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data_preparation',
        ),
    ]
