# Generated by Django 4.2.1 on 2023-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deskriptif', '0003_delete_data_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=100)),
                ('kel', models.FloatField()),
                ('tek', models.FloatField()),
                ('wkt', models.FloatField()),
                ('sh', models.FloatField()),
                ('sdt', models.FloatField()),
                ('tsqr', models.FloatField()),
                ('keterangan', models.CharField(max_length=100)),
                ('d1', models.FloatField()),
                ('d2', models.FloatField()),
                ('d3', models.FloatField()),
                ('d4', models.FloatField()),
                ('variabel', models.CharField(max_length=100)),
            ],
        ),
    ]
